# Generated by Django 3.2.9 on 2021-11-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rental_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_state_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('rental_state_type', models.CharField(choices=[('C', 'COMERCIAL'), ('R', 'RESIDENCIAL')], default='R', max_length=1)),
                ('property_type', models.CharField(choices=[('AP', 'APARTAMENTO'), ('C', 'CASA'), ('CC', 'CASA DE CONDOMÍNIO'), ('CO', 'COBERTURA'), ('FL', 'FLAT'), ('SO', 'SOBRADO')], default='APARTAMENTO', max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('footage', models.CharField(max_length=100)),
                ('unit', models.CharField(default='m2', max_length=2)),
                ('number_of_rooms', models.CharField(max_length=10)),
                ('number_of_bathrooms', models.CharField(max_length=10)),
                ('garage_for_how_many_cars', models.CharField(max_length=10)),
            ],
        ),
    ]
