# Generated by Django 3.2.9 on 2021-11-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_state', '0007_alter_rental_state_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental_state',
            name='property_type',
        ),
        migrations.AddField(
            model_name='rental_state',
            name='residential_type',
            field=models.CharField(choices=[('AP', 'APARTAMENTO'), ('CA', 'CASA'), ('CC', 'CASA DE CONDOMÍNIO'), ('CO', 'COBERTURA'), ('FL', 'FLAT'), ('SO', 'SOBRADO')], default='AP', max_length=2),
        ),
    ]
