# Generated by Django 3.2.9 on 2021-11-23 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_state', '0008_auto_20211122_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental_state',
            old_name='residential_type',
            new_name='property_type',
        ),
    ]
