# Generated by Django 3.2.9 on 2021-11-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_state', '0009_rename_residential_type_rental_state_property_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rental_state',
            new_name='RentalStateProperty',
        ),
    ]
